import { useCallback, useEffect, useMemo, useState } from 'react'
import './App.css'

const formatMoney = (value) => `$${Number(value || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
const today = new Date()
const toDateInput = (date) => date.toISOString().slice(0, 10)

async function requestJson(url, options) {
  const response = await fetch(url, options)
  const payload = response.status === 204 ? null : await response.json()
  if (!response.ok) throw new Error(payload?.error || 'The request could not be completed.')
  return payload
}

function App() {
  const [authenticated, setAuthenticated] = useState(false)
  const [checkingSession, setCheckingSession] = useState(true)
  const [from, setFrom] = useState(toDateInput(new Date(today.getFullYear(), today.getMonth(), 1)))
  const [to, setTo] = useState(toDateInput(today))
  const [report, setReport] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    const authError = params.get('auth_error')
    requestJson('/api/auth/session').then((session) => {
      setAuthenticated(session.authenticated)
      if (authError) setError(authError)
      if (!session.authenticated && !authError) setError('Deriv authorization did not create a session. Check the Vercel callback and Redis configuration.')
    }).catch(() => setError(authError || 'Unable to check your Deriv session.')).finally(() => setCheckingSession(false))
  }, [])

  const loadReport = useCallback(async () => {
    if (from > to) return setError('The start date must be before the end date.')
    setLoading(true)
    setError('')
    try { setReport(await requestJson(`/api/markup/statistics?start_date=${from}&end_date=${to}`)) }
    catch (requestError) { setError(requestError.message) }
    finally { setLoading(false) }
  }, [from, to])

  useEffect(() => { if (authenticated) loadReport() }, [authenticated, loadReport])

  const statistics = report?.app_markup_statistics
  const breakdown = statistics?.breakdown || []
  const applications = report?.app_list || []
  const totalMarkup = statistics?.total_app_markup_usd || 0
  const totalTransactions = statistics?.total_transactions_count || 0
  const metrics = useMemo(() => [
    { label: 'Total markup', value: formatMoney(totalMarkup), note: 'USD equivalent' },
    { label: 'Transactions', value: Number(totalTransactions).toLocaleString(), note: 'In selected period' },
    { label: 'Applications', value: Number(breakdown.length).toLocaleString(), note: 'With markup activity' },
  ], [breakdown.length, totalMarkup, totalTransactions])

  const logout = async () => {
    await requestJson('/api/auth/logout', { method: 'POST' })
    setAuthenticated(false)
    setReport(null)
  }

  if (checkingSession) return <main className="auth-shell"><section className="auth-panel"><div className="eyebrow">DERIV / APPLICATION MARKUP</div><h1>Completing your Deriv sign in.</h1><p className="lead">Checking the secure session and preparing your application insights.</p></section></main>

  if (!authenticated) return <main className="auth-shell"><section className="auth-panel"><div className="eyebrow">DERIV / APPLICATION MARKUP</div><h1>See where your commission is moving.</h1><p className="lead">Sign in securely with Deriv to view markup generated by your registered applications.</p><a className="primary-button login-link" href="/api/auth/login">Continue with Deriv</a>{error && <p className="error">{error}</p>}<p className="fine-print">Authentication uses Deriv OAuth 2.0 with PKCE. Your access token stays on the server.</p></section><aside className="auth-aside"><span>01</span><p>Authorize</p><span>02</span><p>Measure</p><span>03</span><p>Act</p></aside></main>

  return <main className="dashboard-shell"><header className="topbar"><div><div className="eyebrow">DERIV / APPLICATION MARKUP</div><strong>Commission control room</strong></div><div className="account"><span>Authorized account</span><button className="quiet-button" onClick={logout}>Sign out</button></div></header><section className="hero-row"><div><p className="section-kicker">Performance snapshot</p><h1>Commission, clearly.</h1><p className="lead">Markup generated by your registered Deriv applications.</p></div><div className="connection-pill"><i /> OAuth session active</div></section><section className="filters"><div><label htmlFor="from">From</label><input id="from" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></div><div><label htmlFor="to">To</label><input id="to" type="date" value={to} onChange={(event) => setTo(event.target.value)} /></div><button onClick={loadReport} disabled={loading}>{loading ? 'Loading...' : 'Refresh report'}</button></section>{error && <p className="error report-error">{error}</p>}<section className="metrics">{metrics.map((metric) => <article key={metric.label}><span>{metric.label}</span><strong>{metric.value}</strong><small>{metric.note}</small></article>)}</section><section className="content-grid"><article className="chart-panel"><div className="panel-heading"><div><p className="section-kicker">By application</p><h2>Markup distribution</h2></div><span>{from} to {to}</span></div><div className="stat-list">{breakdown.length ? breakdown.map((item) => { const app = applications.find((candidate) => String(candidate.app_id) === String(item.app_id)); return <div key={item.app_id}><span>#{item.app_id} {app?.name || 'Registered application'} · {Number(item.transactions_count || 0).toLocaleString()} transactions</span><strong>{formatMoney(item.app_markup_usd)}</strong></div> }) : <div className="empty-state">No application markup activity for this period.</div>}</div></article><article className="apps-panel"><div className="panel-heading"><div><p className="section-kicker">Authorized account</p><h2>Applications</h2></div><span>{applications.length} registered</span></div><div className="referral-list">{applications.length ? applications.map((app) => <div key={app.app_id}><span>#{app.app_id} {app.name}<small>{app.homepage || app.redirect_uri || 'No URL registered'}</small></span><strong>{formatMoney(breakdown.find((item) => String(item.app_id) === String(app.app_id))?.app_markup_usd)}</strong></div>) : <div className="empty-state">No registered applications returned.</div>}</div></article></section></main>
}

export default App
